using Entities;
using System;
using UnityEngine;

public class Enemy : MonoBehaviour
{
    public event Action<Enemy> Died;

    [SerializeField] private AttackEnemySystem m_attack;
    [SerializeField] private HealthComponent m_health;
    [SerializeField] private EnemyStateMachine m_stateMachine;

    private EnemyData m_data;

    public HealthComponent health => m_health;

    // TODO Add HealthComponent
    // TODO Add Movement
    // TODO Add AttackComponent

    private void Awake()
    {
        m_stateMachine??= new EnemyStateMachine();
    }

    private void OnEnable()
    {
        m_health.Died += OnDied;
    }

    private void OnDisable()
    {
        m_health.Died -= OnDied;
    }

    private void Update()
    {
        if  (m_stateMachine.currentState is EnemyState.Dead || !m_data)
        {
            return;
        }

        UpdateState();
    }

    private void UpdateState()
    {
        
    }

    public void Initialize(EnemyData data, Transform playerTransform)
    {
        m_data = data;
        m_health.Initialize(data.health);
        m_attack.Initialize(data.spell, data.attackTime, m_playerTransform);

        m_playerTransform = playerTransform;
        m_stateMachine ??= new EnemyStateMachine();
    }

    private void OnDied()
    {
       Died?.Invoke(this);
    }

    private bool IsInRange()
    {
        if (!m_playerTransform)
        {
            return false;
        }
    }

    private void OnStateChanged(EnemyState previousState, EnemyState nextState)
    {

    }
    
}
